networks:
  database:
    driver: "bridge"
    name: database

services:
  #DB Mariadb
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: database
    ports:
      - 3306:3306
    networks:
      - database
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s

  #PHPMYADMIN Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 102400000000
    restart: always
    ports:
      - 8080:80
    networks:
      - database

volumes:
  mariadb_data:
