version: "3.7"

networks:
    database:

services:
  
    # db mariadb
    mariadb:
        image: mariadb:latest
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports: 
            - 3306:3306
        networks: 
            - database

    #PHPMYADMIN  Service
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
          PMA_HOST: mariadb
          PMA_USER: ${DB_USERNAME}
          PMA_PASSWORD: ${DB_PASSWORD}
          UPLOAD_LIMIT: 102400000000
      restart: always
      ports:
        - 8080:80
      networks:
        - database

