networks:
  database:
    driver: "bridge"
    name: database

services:
  #DB Mariadb
  mariadb:
    platform: 
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - database
    volumes:
      - mariadb_data:/var/lib/mysql:rw

  #PHPMYADMIN Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 102400000000
    restart: always
    ports:
      - 8080:80
    networks:
      - database

volumes:
  mariadb_data:
